<?php

return [
    'show_warnings' => false,
    'orientation' => 'portrait',
    'defines' => [
        'font_dir' => storage_path('fonts/'),
        'font_cache' => storage_path('fonts/'),
        'temp_dir' => storage_path('app/temp/'),
        'chroot' => base_path(),
        'enable_font_subsetting' => false,
        'pdf_backend' => 'CPDF',
        'default_media_type' => 'screen',
        'default_paper_size' => 'a4',
        'default_font' => 'serif',
        'dpi' => 96,
        'enable_php' => false,
        'enable_javascript' => false,
        'enable_remote' => false,
        'font_height_ratio' => 1.1,
        'enable_html5_parser' => false,
        'is_remote_enabled' => false,
        'is_font_subsetting_enabled' => false,
        'is_php_enabled' => false,
        'is_javascript_enabled' => false,
        'is_html5_parser_enabled' => false,
        'log_output_file' => storage_path('logs/dompdf.log'),
        'default_font_size' => 12,
        'default_font' => 'serif',
        'default_monospace_font' => 'monospace',
        'default_monospace_font_size' => 10,
        'memory_limit' => '128M',
        'max_execution_time' => 30,
        'enable_css_float' => false,
        'enable_font_subsetting' => false,
        'pdf_backend' => 'CPDF',
        'default_media_type' => 'screen',
        'default_paper_size' => 'a4',
        'default_font' => 'serif',
        'dpi' => 96,
        'enable_php' => false,
        'enable_javascript' => false,
        'enable_remote' => false,
        'font_height_ratio' => 1.1,
        'enable_html5_parser' => false,
        'is_remote_enabled' => false,
        'is_font_subsetting_enabled' => false,
        'is_php_enabled' => false,
        'is_javascript_enabled' => false,
        'is_html5_parser_enabled' => false,
    ],
    
    // Additional configuration for cPanel compatibility
    'options' => [
        'isRemoteEnabled' => false,
        'isPhpEnabled' => false,
        'isJavascriptEnabled' => false,
        'isHtml5ParserEnabled' => false,
        'isFontSubsettingEnabled' => false,
        'defaultFont' => 'serif',
        'defaultFontSize' => 12,
        'defaultMonospaceFont' => 'monospace',
        'defaultMonospaceFontSize' => 10,
        'memoryLimit' => '128M',
        'maxExecutionTime' => 30,
        'enableCssFloat' => false,
        'tempDir' => storage_path('app/temp'),
        'fontDir' => storage_path('fonts'),
        'fontCache' => storage_path('fonts'),
        'chroot' => base_path(),
        'logOutputFile' => storage_path('logs/dompdf.log'),
    ]
]; 